github: [metadata]
encoding: UTF-8
kramdown:
 input: GFM
 hard_wrap: false
 future: true
 jailed: false
 gfm_quirks: paragraph_end
remote_theme: deadflowers/jekyll-theme-basically-basic

lang: en-US
description: an area for notes and projects
title: ray kooyenga github
baseurl: "/"
url: "https://rkooyenga.github.io"
logo: https://avatars.githubusercontent.com/u/6174603
# Site Author
author: 
  name: Ray Kooyenga
  email: gmc5oz4k7@mozmail.com
  picture: https://avatars.githubusercontent.com/u/9654073
  twitter: rayktweets
  github_username: rkooyenga
  links:
    - title: Twitter
      url: https://twitter.com/rayktweets
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://instagram.com/raykooyenga
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/rkooyenga
      icon: fab fa-github-square

plugins:
 - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-pwa-plugin
  - jekyll-tagging-related_posts
  - jekyll-target-blank
  - jekyll-postfiles
  - jekyll-og-image

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/rayktweets
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/raykooyenga
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/rkooyenga
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

links_to_prev_next: true

jekyll-theme-basically-basic:
  date_format: "%a, %b %-d, %Y"
  social_links:
    - { platform: github, user_url: "https://github.com/rkooyenga/" }
    - { platform: twitter, user_url: "https://twitter.com/rayktweets/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@raykooyenga/" }

skin: steel
tagline: a ray kooyenga site

github_edit_url: "https://github.com/rkooyenga/rkooyenga.github.io/blob/master/"

feed:
  posts_limit: 1000
permalink: "/:title"

#pwa:
#  enabled: true # Optional
#  sw_src_filepath: service-worker.js # Optional
#  sw_dest_filename: service-worker.js # Optional
#  dest_js_directory: assets/js # Required
#  precache_recent_posts_num: 5 # Optional
#  precache_glob_directory: / # Optional
 # precache_glob_patterns: # Optional
  #  - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
  #  - index.html
  # precache_glob_ignores: # Optional
   # - sw-register.js
   # - "fonts/**/*"

og_image:
  output_dir: "assets/images/og"
#  image: "/assets/image"
#  domain: "rkooyenga.github.io"
  border_bottom:
    width: 20
    fill:
#      - "#820C02"
#      - "#A91401"
#      - "#D51F06"
#      - "#DE3F24"
#      - "#EDA895"

tag_page_layout: tag_page
tag_page_dir: tag
ignored_tags: [tags,to,ignore]
